<?php

session_start();

include("../config/db.php");
include("../includes/auth.php");

if(
    !isset($_SESSION['role']) ||
    $_SESSION['role']!="Admin"
)
{
    header("Location:../index.php");
    exit();
}

if(!isset($_GET['id']))
{
    header("Location:reports.php");
    exit();
}

$id = intval($_GET['id']);

/* ==========================================
   FETCH REPORT + EMPLOYEE + WORKSHOP DETAILS
========================================== */

$sql = "

SELECT

r.id,
r.report_name,
r.report_year,
r.generated_date,
r.status,
r.json_path,

e.ic_no,
e.name,
e.phone,
e.designation,
e.email,

w.workshop_name,
w.workshop_year,
w.attended_date,
w.attendance_status,
w.remarks,

g.name AS generated_by_name

FROM reports r

INNER JOIN employee e
ON r.employee_ic = e.ic_no

INNER JOIN workshops w
ON e.ic_no = w.ic_no
AND w.workshop_year = r.report_year

LEFT JOIN employee g
ON r.generated_by = g.ic_no

WHERE r.id = ?

";

$stmt = $conn->prepare($sql);

$stmt->bind_param("i",$id);

$stmt->execute();

$result = $stmt->get_result();

if($result->num_rows==0)
{
    die("Report not found.");
}

$row = $result->fetch_assoc();

?>

<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<title>Report Details</title>

<link rel="stylesheet" href="../css/sidebar.css">
<link rel="stylesheet" href="../css/navbar.css">
<link rel="stylesheet" href="../css/dashboard.css">

<link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

</head>

<body>

<?php include("../includes/sidebar.php"); ?>
<?php include("../includes/navbar.php"); ?>

<div class="content">

<div class="glass-header">

<div>

<h2>

<i class="fa-solid fa-file-circle-check"></i>

Report Details

</h2>

<p>

Review employee information before verifying the report.

</p>

</div>

</div>

<div class="dashboard-middle">

<!-- =====================================================
     EMPLOYEE INFORMATION
====================================================== -->

<div class="activity-box">

<h3>

<i class="fa-solid fa-user"></i>

Employee Information

</h3>

<table class="activity-table">

<tr>

<td><strong>IC Number</strong></td>

<td><?php echo htmlspecialchars($row['ic_no']); ?></td>

</tr>

<tr>

<td><strong>Name</strong></td>

<td><?php echo htmlspecialchars($row['name']); ?></td>

</tr>

<tr>

<td><strong>Designation</strong></td>

<td><?php echo htmlspecialchars($row['designation']); ?></td>

</tr>

<tr>

<td><strong>Phone</strong></td>

<td><?php echo htmlspecialchars($row['phone']); ?></td>

</tr>

<tr>

<td><strong>Email</strong></td>

<td><?php echo htmlspecialchars($row['email']); ?></td>

</tr>

</table>

</div>

<!-- =====================================================
     WORKSHOP INFORMATION
====================================================== -->

<div class="activity-box">

<h3>

<i class="fa-solid fa-book-open"></i>

Workshop Information

</h3>

<table class="activity-table">

<tr>

<td><strong>Workshop</strong></td>

<td><?php echo htmlspecialchars($row['workshop_name']); ?></td>

</tr>

<tr>

<td><strong>Workshop Year</strong></td>

<td><?php echo htmlspecialchars($row['workshop_year']); ?></td>

</tr>

<tr>

<td><strong>Attendance Date</strong></td>

<td>

<?php

if(empty($row['attended_date']))
{
    echo "<span class='status-orange'>Not Updated</span>";
}
else
{
    echo date("d M Y",strtotime($row['attended_date']));
}

?>

</td>

</tr>

<tr>

<td><strong>Attendance Status</strong></td>

<td>

<?php

if($row['attendance_status']=="Attended")
{
    echo "<span class='status-green'><i class='fa-solid fa-circle-check'></i> Attended</span>";
}
elseif($row['attendance_status']=="Pending")
{
    echo "<span class='status-orange'><i class='fa-solid fa-clock'></i> Pending</span>";
}
else
{
    echo "<span class='status-red'><i class='fa-solid fa-circle-xmark'></i> Absent</span>";
}

?>

</td>

</tr>

<tr>

<td><strong>Remarks</strong></td>

<td>

<?php

if(trim($row['remarks'])=="")
{
    echo "-";
}
else
{
    echo nl2br(htmlspecialchars($row['remarks']));
}

?>

</td>

</tr>

</table>

</div>

</div>

<!-- =====================================================
     REPORT INFORMATION
====================================================== -->

<div class="dashboard-middle">

<div class="activity-box">

<h3>

<i class="fa-solid fa-file-lines"></i>

Report Information

</h3>

<table class="activity-table">

<tr>

<td><strong>Report Name</strong></td>

<td><?php echo htmlspecialchars($row['report_name']); ?></td>

</tr>

<tr>

<td><strong>Report Year</strong></td>

<td><?php echo htmlspecialchars($row['report_year']); ?></td>

</tr>

<tr>

<td><strong>Generated By</strong></td>

<td>

<?php

echo htmlspecialchars($row['generated_by_name']);

?>

</td>

</tr>

<tr>

<td><strong>Generated Date</strong></td>

<td>

<?php

echo date("d M Y h:i A",strtotime($row['generated_date']));

?>

</td>

</tr>

<tr>

<td><strong>Status</strong></td>

<td>

<?php

if($row['status']=="Verified")
{
?>

<span class="status-green">

<i class="fa-solid fa-circle-check"></i>

Verified

</span>

<?php
}
else
{
?>

<span class="status-orange">

<i class="fa-solid fa-clock"></i>

Pending Verification

</span>

<?php
}

?>

</td>

</tr>

</table>

</div>

<!-- =====================================================
     JSON REPORT
====================================================== -->

<div class="activity-box">

<h3>

<i class="fa-solid fa-file-code"></i>

Generated JSON Report

</h3>

<table class="activity-table">

<tr>

<td><strong>File Name</strong></td>

<td>

<?php

echo basename($row['json_path']);

?>

</td>

</tr>

<tr>

<td><strong>Storage Location</strong></td>

<td>

reports/

</td>

</tr>

<tr>

<td><strong>Availability</strong></td>

<td>

<?php

if(file_exists($row['json_path']))
{
?>

<span class="status-green">

<i class="fa-solid fa-circle-check"></i>

Available

</span>

<?php
}
else
{
?>

<span class="status-red">

<i class="fa-solid fa-circle-xmark"></i>

Missing

</span>

<?php
}

?>

</td>

</tr>

</table>

<br>

<div class="button-group">

<a

href="view_json.php?id=<?php echo $row['id']; ?>"

class="btn-save">

<i class="fa-solid fa-eye"></i>

View JSON

</a>

<a

href="<?php echo $row['json_path']; ?>"

download

class="btn-report">

<i class="fa-solid fa-download"></i>

Download JSON

</a>

</div>

</div>

</div>

<!-- =====================================================
     ACTION BUTTONS
====================================================== -->

<!-- =====================================================
     ACTION BUTTONS
====================================================== -->

<br>

<div class="activity-box" style="max-width:900px;margin:auto;text-align:center;">

<h3>

<i class="fa-solid fa-shield-check"></i>

Report Verification

</h3>

<p style="margin:20px 0 30px;color:#dbeafe;font-size:16px;">

Please review the employee details, workshop attendance and remarks before taking any action.

</p>

<div style="display:flex;
justify-content:center;
align-items:center;
gap:18px;
flex-wrap:wrap;">

<?php

if($row['status']=="Pending")
{

?>

<a

href="verify.php?id=<?php echo $row['id']; ?>"

class="btn-save"

onclick="return confirm('Verify this report?');"

>

<i class="fa-solid fa-circle-check"></i>

Verify

</a>

<a

href="reject.php?id=<?php echo $row['id']; ?>"

class="btn-back"

style="background:#dc2626;"

onclick="return confirm('Reject this report?');"

>

<i class="fa-solid fa-circle-xmark"></i>

Reject

</a>

<?php

}
else
{

?>

<span class="status-green"
style="padding:14px 25px;font-size:16px;">

<i class="fa-solid fa-circle-check"></i>

Already Verified

</span>

<?php

}

?>

<a

href="reports.php"

class="btn-report"

>

<i class="fa-solid fa-arrow-left"></i>

Back

</a>

</div>

</div>

<?php

?>

<a

href="reports.php"

class="btn-back"

>

<i class="fa-solid fa-arrow-left"></i>

Back to Pending Reports

</a>

</div>

</div>

</div>

</body>

</html>

<?php

$stmt->close();

$conn->close();

?>