<?php

session_start();

include("../config/db.php");
include("../includes/auth.php");

if($_SESSION['role']!="Admin")
{
    header("Location:../index.php");
    exit();
}

$sql="

SELECT

r.id,
r.report_name,
r.report_year,
r.generated_date,
r.status,

e.name,
e.ic_no

FROM reports r

INNER JOIN employee e

ON r.employee_ic=e.ic_no

WHERE r.status='Pending'

ORDER BY r.generated_date DESC

";

$result=mysqli_query($conn,$sql);

?>

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>Pending Reports</title>

<link rel="stylesheet" href="../css/sidebar.css">
<link rel="stylesheet" href="../css/navbar.css">
<link rel="stylesheet" href="../css/dashboard.css">

<link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

<script src="../js/search.js"></script>

</head>

<body>

<?php include("../includes/sidebar.php"); ?>
<?php include("../includes/navbar.php"); ?>

<div class="content">

<h2>

<i class="fa-solid fa-file-circle-exclamation"></i>

Pending Reports

</h2>

<p>

Verify reports generated by the Karyashala Admin.

</p>

<input

type="text"

id="searchBox"

class="search-box"

placeholder="Search employee or report..."

>

<div class="activity-box">

<table

class="activity-table"

id="employeeTable"

>

<tr>

<th>IC No</th>

<th>Employee</th>

<th>Report</th>

<th>Year</th>

<th>Status</th>

<th>Action</th>

</tr>

<?php

while($row=mysqli_fetch_assoc($result))

{

?>

<tr>

<td>

<?php echo $row['ic_no']; ?>

</td>

<td>

<?php echo $row['name']; ?>

</td>

<td>

<?php echo $row['report_name']; ?>

</td>

<td>

<?php echo $row['report_year']; ?>

</td>

<td>

<span class="status-orange">

Pending

</span>

</td>

<td>

<a

href="verify.php?id=<?php echo $row['id']; ?>"

class="btn-save"

onclick="return confirm('Verify this report?');"

>

<i class="fa-solid fa-circle-check"></i>

Verify

</a>

</td>

</tr>

<?php

}

?>

</table>

</div>

</div>

</body>

</html>

<?php

$conn->close();

?>