<?php

session_start();

include("../config/db.php");
include("../includes/auth.php");

if(
    !isset($_SESSION['role']) ||
    $_SESSION['role']!="Admin"
)
{
    header("Location:../index.php");
    exit();
}

if(!isset($_GET['id']))
{
    header("Location:reports.php");
    exit();
}

$id = intval($_GET['id']);

$sql = "

SELECT

report_name,
report_year,
status,
json_path

FROM reports

WHERE id=?

";

$stmt = $conn->prepare($sql);

$stmt->bind_param("i",$id);

$stmt->execute();

$result = $stmt->get_result();

if($result->num_rows==0)
{
    die("Report not found.");
}

$report = $result->fetch_assoc();

if(!file_exists("../".$report['json_path']))
{
    die("JSON file not found.");
}

$json = file_get_contents("../".$report['json_path']);

$data = json_decode($json,true);

?>

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>View JSON Report</title>

<link rel="stylesheet" href="../css/dashboard.css">

<link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

</head>

<body>

<?php include("../includes/navbar.php"); ?>

<?php include("../includes/sidebar.php"); ?>

<div class="content">

<div class="form-card">

<h2>

<i class="fa-solid fa-file-code"></i>

<?php echo $report['report_name']; ?>

</h2>

<br>

<h3>Employee Details</h3>

<table class="details-table">

<tr>

<th>IC Number</th>

<td><?php echo $data['employee']['ic_no']; ?></td>

</tr>

<tr>

<th>Name</th>

<td><?php echo $data['employee']['name']; ?></td>

</tr>

<tr>

<th>Phone</th>

<td><?php echo $data['employee']['phone']; ?></td>

</tr>

<tr>

<th>Designation</th>

<td><?php echo $data['employee']['designation']; ?></td>

</tr>

<tr>

<th>Email</th>

<td><?php echo $data['employee']['email']; ?></td>

</tr>

</table>

<br>

<h3>Workshop Details</h3>

<table class="details-table">

<tr>

<th>Workshop</th>

<td><?php echo $data['workshop']['workshop_name']; ?></td>

</tr>

<tr>

<th>Year</th>

<td><?php echo $data['workshop']['workshop_year']; ?></td>

</tr>

<tr>

<th>Attendance Date</th>

<td><?php echo $data['workshop']['attended_date']; ?></td>

</tr>

<tr>

<th>Status</th>

<td><?php echo $data['workshop']['attendance_status']; ?></td>

</tr>

<tr>

<th>Remarks</th>

<td><?php echo $data['workshop']['remarks']; ?></td>

</tr>

</table>

<br>

<h3>Generated By</h3>

<table class="details-table">

<tr>

<th>IC Number</th>

<td><?php echo $data['generated_by']['ic_no']; ?></td>

</tr>

<tr>

<th>Name</th>

<td><?php echo $data['generated_by']['name']; ?></td>

</tr>

<tr>

<th>Generated Date</th>

<td><?php echo $data['generated_date']; ?></td>

</tr>

</table>

<br>

<div class="button-group">

<a href="reports.php" class="btn-back">

<i class="fa-solid fa-arrow-left"></i>

Back

</a>

<?php

if($report['status']=="Pending")
{

?>

<a

href="verify.php?id=<?php echo $id; ?>"

class="btn-save">

<i class="fa-solid fa-circle-check"></i>

Verify Report

</a>

<?php

}

else

{

?>

<button class="btn-save" disabled>

Verified

</button>

<?php

}

?>

</div>

</div>

</div>

</body>

</html>